### ISSUE TITLE
Multiple Word Practice Feature

### ISSUE THREAD

**Issue by Le-SirH** [DaveDabko/Specific-Typing-Practise#3]
### Multiple Word Practice Feature
Currently, after a level of difficulty is chosen, that word is repeated over a few times to type. Should users have an option to repeatedly type one word of their chosen difficulty & to mix it up at random levels?

**Comment by DaveDabko** [comment]
Probably. I'll see what i can do since I have lots of time this weekend.

**Comment by DaveDabko** [comment]
Made a randomise mode. I realise now that that is not what you meant. If I can be bothered, I will add a way to let the user select specific words from any level and mix it up.
